stages:
  - initialization
  - test.smoke
  - publish
  - push
  - final

default:
  before_script:
    - ci_scripts/before_script.sh
  services:
    - $PIPELINE_DEPS_REGISTRY/docker:18.09-dind
  image: $RUNNER_IMAGE_X86_64
################################################
# Default variables used by all jobs unless they
# are overridden by the job
#
#  - .5-1 cpu
#  - 1.9GB of memory with no elasticity
#  - poll timeout of 15 minutes (to release capacity)
################################################
variables:
  DOCKER_HOST: tcp://localhost:2375
  KUBERNETES_CPU_REQUEST: 500m
  KUBERNETES_CPU_LIMIT: 1000m
  KUBERNETES_MEMORY_REQUEST: 1900000000
  KUBERNETES_MEMORY_LIMIT: 1900000000
  KUBERNETES_POLL_TIMEOUT: 1200
################################################
# For Docker Compose Tests, provide a kubernetes
# sizing of:
#
#  - 95% of a cpu up to 4x (380%)
#  - 1.9g of memory with no elasticity
################################################
# variables:
#   KUBERNETES_CPU_REQUEST: 950m
#   KUBERNETES_CPU_LIMIT: 3800m
#   KUBERNETES_MEMORY_REQUEST: 1900000000
#   KUBERNETES_MEMORY_LIMIT: 1900000000


################################################
#   _____ _   _ _____ _______
#  |_   _| \ | |_   _|__   __|
#    | | |  \| | | |    | |
#    | | | . ` | | |    | |
#   _| |_| |\  |_| |
#  |_____|_| \_|_____|  |_|
#
################################################
# Note: Platform agnostic
intel.i.checks:
  stage: initialization
  script:
    - ci_scripts/if_readme_only.sh
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      # - $CI_COMMIT_MESSAGE =~ /\[skip build\]/

intel.i.unmerged:
  stage: initialization
  script:
    - ci_scripts/unmerged_changes.sh
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/

# intel.i.shellcheck:
#   stage: initialization
#   script:
#     - ci_scripts/shellcheck.sh
#   except:
#     variables:
#       - $CI_COMMIT_REF_NAME =~ /^workspace.*/
#       - $CI_COMMIT_MESSAGE =~ /\[skip build\]/

intel.i.chartlinter:
  stage: initialization
  script:
    - ci_scripts/helm_chart_linter.sh
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/
      - $CI_COMMIT_TAG

intel.i.shfmt:
  stage: initialization
  script:
    - ci_scripts/shfmt.sh --diff
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^workspace.*/
      - $CI_COMMIT_MESSAGE =~ /\[skip build\]/

################################################
#                  SMOKE TESTS
################################################

intel.t.pingaccess:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingaccess
  retry: 2

intel.t.pingauthorize:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingauthorize
  retry: 2

intel.t.pingauthorizepap:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingauthorizepap
  retry: 2

intel.t.pingdataconsole:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdataconsole
  retry: 2

intel.t.pingdatagovernance:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdatagovernance
  retry: 2

intel.t.pingdatagovernancepap:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdatagovernancepap
  retry: 2

intel.t.pingdatasync:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdatasync
  retry: 2

intel.t.pingdelegator:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdelegator
  retry: 2

intel.t.pingdirectory:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdirectory
  retry: 2

intel.t.pingdirectoryproxy:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingdirectoryproxy
  retry: 2

intel.t.pingfederate:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingfederate
  retry: 2

intel.t.pingtoolkit:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product pingtoolkit
  retry: 2

################################################
#   _____       _     _ _     _
#  |  __ \     | |   | (_)   | |
#  | |__) |   _| |__ | |_ ___| |__
#  |  ___/ | | | '_ \| | / __| '_ \
#  | |   | |_| | |_) | | \__ \ | | |
#  |_|    \__,_|_.__/|_|_|___/_| |_|
#
################################################

p.charts:
  stage: publish
  before_script:
    - git config --global user.name "${GITLAB_USER}"
    - git config --global user.email "${GITLAB_USER}@pingidentity.com"
  script:
    - ci_scripts/release_charts.sh
  rules:
    - if: $RELEASE == "true"

p.github:
  stage: push
  before_script:
    - git config --global user.name "${GITLAB_USER}"
    - git config --global user.email "${GITLAB_USER}@pingidentity.com"
  script:
    - git --version
    - ci_scripts/push_to_github.sh
    #- ci_scripts/deploy_docs.sh

################################################
#   ______ _____ _   _          _
#  |  ____|_   _| \ | |   /\   | |
#  | |__    | | |  \| |  /  \  | |
#  |  __|   | | | . ` | / /\ \ | |
#  | |     _| |_| |\  |/ ____ \| |____
#  |_|    |_____|_| \_/_/    \_\______|
################################################

clean-k8s:
  stage: final
  script:
    - ci_scripts/cleanup_kubernetes.sh
  when: always
