{{- include "pinglib.configmap" (list . "pingfederate-admin") -}}


{{- define "pingfederate-admin.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
{{ include "pinglib.configmap.pingfederate" . }}
{{- end -}}
