apiVersion: v1
entries:
  devops:
  - apiVersion: v2
    appVersion: "2.0"
    created: "2020-11-13T17:40:26.372268-06:00"
    description: All Ping Identity product images with integration
    digest: 3772bd01ff4be58b4b54c0d5ed106b0dbe794973f45bb0d6121d69768027314d
    home: https://devops.pingidentity.com/
    name: devops
    type: application
    urls:
    - https://helm.pingidentity.com/devops/devops-0.2.0.tgz
    version: 0.2.0
generated: "2020-11-13T17:40:26.356063-06:00"
