{{- range (list "pingaccess-admin" "pingaccess-engine" "pingauthorize" "pingdatagovernance" "pingdatasync" "pingdirectory" "pingdirectoryproxy" "pingfederate-admin" "pingfederate-engine" ) }}
    {{- if (merge (index $.Values . ) $.Values.global).privateCert.generate }}
        {{- include "pinglib.private-cert" (list $ .) }}
---
    {{- end }}
{{- end }}


{{- define "pingaccess-admin.private-cert" -}}{{- end -}}
{{- define "pingaccess-engine.private-cert" -}}{{- end -}}
{{- define "pingauthorize.private-cert" -}}{{- end -}}
{{- define "pingdatagovernance.private-cert" -}}{{- end -}}
{{- define "pingdatasync.private-cert" -}}{{- end -}}
{{- define "pingdirectory.private-cert" -}}{{- end -}}
{{- define "pingdirectoryproxy.private-cert" -}}{{- end -}}
{{- define "pingfederate-admin.private-cert" -}}{{- end -}}
{{- define "pingfederate-engine.private-cert" -}}{{- end -}}
