{{- if (merge (index .Values "pingdatagovernance") .Values.global).ingress.enabled }}
{{- include "pinglib.ingress" (list . "pingdatagovernance") -}}
{{- end -}}



{{- define "pingdatagovernance.ingress" -}}
{{- end -}}