{{- include "pinglib.workload" (list . "pingdatagovernance") -}}



{{- define "pingdatagovernance.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.addreleasename" (append . "pingdatagovernance") }}
{{- end -}}