{{- include "pinglib.service-cluster" (list . "pingdirectory") -}}


{{- define "pingdirectory.service-cluster" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  selector:
    clusterIdentifier: {{ include "pinglib.addreleasename" (append . "pingdirectory") }}
{{- end -}}