{{- include "pinglib.service-cluster" (list . "pingdatasync") -}}


{{- define "pingdatasync.service-cluster" -}}
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  selector:
    clusterIdentifier: {{ include "pinglib.addreleasename" (append . "pingdatasync") }}
{{- end -}}