{{- include "pinglib.workload" (list . "pingdatasync") -}}



{{- define "pingdatasync.workload" -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.addreleasename" (append . "pingdatasync") }}
{{- end -}}